# Generated by Django 4.2.4 on 2023-08-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_remove_board_coordinates_alter_board_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boarddetails',
            name='current_pointer',
            field=models.BooleanField(default=False),
        ),
    ]
