# Generated by Django 4.2.4 on 2023-08-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_boarddetails_current_pointer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boarddetails',
            name='current_pointer',
            field=models.CharField(default='enabled', max_length=100),
        ),
    ]
